### ISSUE TITLE
Kernel crashed while executing code

### ISSUE THREAD

**Issue by ngocuyenngn** [visualdatabase/fastdup#24]
Hi,
Thank you for looking into my issue. I was trying to run the following code:
`
import fastdup
`
`
fastdup.run_kmeans(input_dir='./data', work_dir = ./out')
`
then it shows the following error

> Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

The log is as below:

Found total 38 images to run on

error 13:19:39.756: Disposing session as kernel process died ExitCode: undefined, Reason: 
/anaconda3/envs/scan/lib/python3.7/site-packages/traitlets/traitlets.py:2415: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning,
/anaconda3/envs/scan/lib/python3.7/site-packages/traitlets/traitlets.py:2369: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '298cec57-193d-4bb0-b39b-bad7277157b3' instead of 'b"298cec57-193d-4bb0-b39b-bad7277157b3"'.
  FutureWarning,

error 13:19:39.757: Raw kernel process exited code: undefined
error 13:19:39.759: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:1376085)
	at /.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:1395137
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:1395122)
	at y.dispose (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:1388604)
	at /.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:578260
	at t.swallowExceptions (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:1001797)
	at dispose (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:578238)
	at t.RawSession.dispose (/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:583202)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 13:19:39.759: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 13:19:39.760: Cancel all remaining cells true || Error || undefined
info 13:19:39.760: Cancel pending cells
info 13:19:39.761: Cell 4 executed with state Error

**Comment by ngocuyenngn** [comment]
1.

**Comment by visualdatabase** [comment]
Hi @ngocuyenngn we do not support conda python, can you try to run using regular python and see if it works for you? Also run on a python terminal (not a jupyter notebook) with verbose=1 and we will try to understand what is going on. Send me the output.
