### ISSUE TITLE
Your system is missing some depdencies, please pip install matplotlib matplotlib-inline torchvision

### ISSUE THREAD

**Issue by sergii-bond** [visualdatabase/fastdup#4]
Running in docker again.

```
Your system is missing some depdencies, please pip install matplotlib matplotlib-inline torchvision
Traceback (most recent call last):
  File "./run.py", line 5, in <module>                                                                                                                        
    fastdup.create_components_gallery('out', save_path='.')                    #create visualiaiton of connected components
  File "/usr/local/lib/python3.8/dist-packages/fastdup/__init__.py", line 733, in create_components_gallery
    for i,(j,row) in tqdm(enumerate(subdf.iterrows()), total=num_images):      
AttributeError: 'int' object has no attribute 'iterrows'   
```

torch is quite a heavy dependency.
```
Collecting torch==1.12.0
  Downloading torch-1.12.0-cp38-cp38-manylinux1_x86_64.whl (776.3 MB)
```

I installed them as suggested inside docker and it completed the run.

**Comment by dbickson** [comment]
Hi @sergii-bond you are absolutely right we have released another docker to fix this. v101.
